In [1]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pandas as pd

In [9]:
data = pd.read_csv(r'C:\Users\x\Documents\program\Python\Project\Asset\cardio_train.csv', sep=';')
data

          id    age  gender  height  weight  ...  gluc  smoke  alco  active  cardio
0          0  18393       2     168    62.0  ...     1      0     0       1       0
1          1  20228       1     156    85.0  ...     1      0     0       1       1
2          2  18857       1     165    64.0  ...     1      0     0       0       1
3          3  17623       2     169    82.0  ...     1      0     0       1       1
4          4  17474       1     156    56.0  ...     1      0     0       0       0
...      ...    ...     ...     ...     ...  ...   ...    ...   ...     ...     ...
69995  99993  19240       2     168    76.0  ...     1      1     0       1       0
69996  99995  22601       1     158   126.0  ...     2      0     0       1       1
69997  99996  19066       2     183   105.0  ...     1      0     1       0       1
69998  99998  22431       1     163    72.0  ...     2      0     0       0       1
69999  99999  20540       1     170    72.0  ...     1      0     0       1       0

[70000 rows x 13 columns]

In [10]:
X = data.drop(['id', 'cardio'], axis=1)
X['age'] = (X['age'] / 365).round().astype(int)
X['gender'] = X['gender'].map({1: 0, 2: 1})
y = data['cardio']

In [13]:
X

       age  gender  height  weight  ...  gluc  smoke  alco  active
0       50       1     168    62.0  ...     1      0     0       1
1       55       0     156    85.0  ...     1      0     0       1
2       52       0     165    64.0  ...     1      0     0       0
3       48       1     169    82.0  ...     1      0     0       1
4       48       0     156    56.0  ...     1      0     0       0
...    ...     ...     ...     ...  ...   ...    ...   ...     ...
69995   53       1     168    76.0  ...     1      1     0       1
69996   62       0     158   126.0  ...     2      0     0       1
69997   52       1     183   105.0  ...     1      0     1       0
69998   61       0     163    72.0  ...     2      0     0       0
69999   56       0     170    72.0  ...     1      0     0       1

[70000 rows x 11 columns]

In [14]:
dataflow = Pipeline(steps=[
    ('scale', StandardScaler()),
    ('estimator', LogisticRegression())
])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [16]:
model = dataflow.fit(X_train, y_train)

In [21]:
from sklearn.metrics import accuracy_score
score = model.score(X_test, y_test)
predict = model.predict(X_test)
accuracy = accuracy_score(y_test, predict)
accuracy, score

(0.7196666666666667, 0.7196666666666667)